FROM binwiederhier/ntfy

# Install Nginx
RUN apt-get update && apt-get install -y nginx

# Copy Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Copy your ntfy configuration
COPY server.yml /etc/ntfy/server.yml

# Expose Nginx ports
EXPOSE 80

# Start Nginx and ntfy
CMD service nginx start && ntfy serve
